sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: RwxK2UCwLlkZWpLCuzxEHziyp2P/aht3Zo/9eDnoHOW6h/rlJ3TJQwBjR/sV45qkGY0n7uwvEnuYHYfE7AqWUTquPzWJsbCjz31FKbpKRHvYTrLiP+0lcJDBC+yABpFStzSzAS4dAKWePtOhmmf0vHib1KrEiHf9OPKypZ7OBKApJpplM0iCNnoLAOwI3RIBGQKEXII0Epexg4qzaXUr/ds2Sr2e5yZ6LxG2Wu5TWdZfp1oSAt4s+RRXKI4+fpubVX7cG1/R6lnNfC+npRlp6LTMCwJaPhryYcrmqN+IXaE356mxhjukAqf4pX4ELEUFZ2d7nmfY3Hyw4V2auurb8NWemR67JJgdHTFpaYowNAQ4jC9BW3xXHGjV3SpUT1Dqn7guDPElgDcJpmoxaKoFfpJ9qAF/B1jQnCUTfJp1c9bR2e7dRUFkDZQGWfgU7BG8LWtY31QmhD4YHq/Xxg+vmoiqZxPksJV7mOHASy77u9zX87EEick+BgzWXVdV1Y8jp0HskwynvPzGftt2KYY2NtCrTE+yU0dyiZFiYLM69hzKtxjqocL5E2i9MdcPiivc91i7rlPjHRyHIrCsx3SNgBKzNnX27V5CQZzQElVbNOwfhUpGv1cDu4HkJ/ea+nn52MaaE0LZFGUFqUZdlif6yYD4n+hREKTDTj3FHRRIxXA=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Old-Christmas_1850
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy